name: website deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1 - Checks-out your repository
      - name: Checkout
        uses: actions/checkout@main

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # Step 4 - Builds the site using the latest version of Hugo
      - name: Build
        run: hugo --minify

      # Step 5 - Deploy via scp to Opalstack
      - name: copy website file to Opalstack
        uses: garygrossgarten/github-action-scp@release
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          privateKey: ${{ secrets.KEY }}
        with:
          local: "public/sometimes/index.html"
          remote: "/home/oli/apps/oli_works/sometimes.html"

      # Step 6 - Deploy via scp to Opalstack
      - name: copy htaccess file to Opalstack
        uses: garygrossgarten/github-action-scp@release
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          privateKey: ${{ secrets.KEY }}
        with:
          local: "htaccess.txt"
          remote: "/home/oli/apps/oli_works/.htaccess"

      # Step 7 - copy txt files to Opalstack
      - name: copy txt files to Opalstack
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "static/humans.txt,static/robots.txt"
          target: "/home/oli/apps/oli_works"
          strip_components: 1

